### PR TITLE
Add image path for OKD

### PR DESCRIPTION
**Pull request by hunter86bg**

### CODE REVIEW

**Comment by hunter86bg** [comment]
Most probably there is a newer version of the MongoDB, but I couldn't find any.

**Comment by blues-man** [comment]
Hi @hunter86bg thanks for your PR! Did you tried it on OKD? We're gonna change the flow for 4.10 like [this](https://gist.github.com/blues-man/2570c98ac24e18adf5fd3246b353e63c#file-workshop_debug_4-10-sh-L16), but if this works on OKD 4.9 I'll merge it! Probably we can also use OKD in asciidoc Tabs like [here](https://raw.githubusercontent.com/redhat-scholars/openshift-starter-guides/ocp-4.9/documentation/modules/ROOT/pages/common-explore.adoc)

**Comment by hunter86bg** [comment]
I found it because I'm going over the whole tutorial on my OKD 4.9 (fully updated).

**Comment by hunter86bg** [comment]
@blues-man ,
this was the only way to make it work on OKD 4.9 .
As I'm new in Kubernetes & Openshift , it took me some time to figure out that the image was missing and based on the template I managed to identify which image was needed.

**Comment by blues-man** [comment]
Thanks for your contribution and congrats this looks really great way to start dealing with Kubernetes and OpenShift by investigating, collaborating and contributing :)

**Pull request merged**
